import { NextRequest, NextResponse } from "next/server";
import { IdeasService } from "@hintboard/supabase/services";
import OpenAI from "openai";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

export async function POST(request: NextRequest) {
  try {
    const { ideaIds, organizationId, organizationName } = await request.json();

    if (!ideaIds || !Array.isArray(ideaIds) || ideaIds.length === 0) {
      return NextResponse.json(
        { error: "Please provide an array of idea IDs" },
        { status: 400 },
      );
    }

    if (!organizationId) {
      return NextResponse.json(
        { error: "Organization ID is required" },
        { status: 400 },
      );
    }

    const allIdeas = await IdeasService.getFilteredIdeas(
      organizationId,
      null,
      null,
      "server",
    );

    const selectedIdeas = allIdeas.filter((idea) =>
      ideaIds.includes(idea.idea_id),
    );

    if (selectedIdeas.length === 0) {
      return NextResponse.json(
        { error: "No valid ideas found with the provided IDs" },
        { status: 404 },
      );
    }

    console.log("=== SELECTED IDEAS ===");
    console.dir(selectedIdeas, { depth: null });
    console.log("======================");

    const prompt = buildAnnouncementPrompt(selectedIdeas, organizationName);

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: `You are a professional product-update copywriter for SaaS companies.
You MUST return valid JSON only, matching the schema exactly.`,
        },
        { role: "user", content: prompt },
      ],
      response_format: { type: "json_object" },
      max_tokens: 2000,
      temperature: 0.7,
    });

    const generated = completion?.choices[0]?.message?.content?.trim() || "";
    console.log(
      "=== GENERATED CONTENT ===\n",
      generated,
      "\n======================",
    );

    const parsed = JSON.parse(generated);

    return NextResponse.json({
      success: true,
      title: parsed.title,
      blocks: parsed.blocks,
      ideasProcessed: selectedIdeas.length,
    });
  } catch (error) {
    console.error("Error generating announcement:", error);
    return NextResponse.json(
      {
        error: "Failed to generate announcement",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}

/**
 * Builds an announcement prompt that returns structured JSON
 * with CTA and short, email-style tone.
 */
function buildAnnouncementPrompt(
  ideas: any[],
  organizationName?: string,
): string {
  const orgName = organizationName || "our platform";

  const ideaText = ideas
    .map(
      (idea, idx) => `
${idx + 1}. ${idea.title}
   Type: ${idea.is_bug ? "Bug Fix" : "Feature / Improvement"}
   Status: ${idea.status_name || "No status"}
   Description: ${idea.description || "No description"}
   Topics: ${idea.topics?.map((t: any) => t.name).join(", ") || "None"}
`,
    )
    .join("\n");

  return `Write a friendly, concise **email-style product announcement** for ${orgName}.
It should sound like a human update post that could be sent automatically after a feature ships.

GOAL:
Announce the newly shipped ideas below and include a clear call-to-action block at the end.

OUTPUT FORMAT:
Return a JSON object exactly like this:

{
  "title": "🎉 Dark Mode is Here!",
  "blocks": [
    { "type": "paragraph", "content": "You asked, we built it. Dark Mode is now live for all users!" },
    { "type": "paragraph", "content": "Toggle it in your settings for a more comfortable experience—especially during late-night sessions." },
    { "type": "paragraph", "content": "This idea came from 234 votes on the feedback board. Thanks for helping us improve!" },
    { "type": "cta", "content": "Try Dark Mode Now" },
    { "type": "divider", "content": "" },
    { "type": "paragraph", "content": "Auto-generated by Hintboard AI" }
  ]
}

BLOCK TYPES:
- "paragraph": regular text
- "h2": section heading (optional)
- "bullet-list": each bullet item (optional)
- "divider": visual separator (empty content)
- "cta": single strong call-to-action text (e.g., “Try Dark Mode Now”)

TONE & STYLE:
- Write like a friendly SaaS product team.
- Use short sentences and natural phrasing.
- Include emojis where it feels natural.
- Always add a CTA block (type "cta") encouraging users to check out the feature.
- End with a brief auto-generated note like "Auto-generated by Hintboard AI".
- Do NOT include markdown, bold, or italics—plain text only.
- Only mention the ideas below.

IDEAS TO ANNOUNCE:
${ideaText}

Return ONLY the JSON object.`;
}
